- replaced custom BookRepository with JpaRepository interface
DanilKi/OnlineBookStore pull request #3
Opened 2024-05-13 21:43 UTC by DanilKi

- implemented soft delete concept for the Book entity
- added update & delete by id methods for Book entity to BookController & BookServiceImpl classes
- added liquibase support

2024-05-14 05:46 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-14 05:46 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
Add Table annotation with name

2024-05-14 05:46 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/model/Book.java
>  @Data
Don't use `@Data` for entities, read article about it

2024-05-14 05:46 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
Use `@SQLRestriction` instead of `@Where`

2024-05-14 05:46 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.getTitle());
It looks like mapper can implement this logic

2024-05-14 05:46 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-book-table.yml
> +            tableName: book
Table name should be plural
```suggestion
            tableName: books
```

2024-05-14 05:46 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/controller/BookController.java
>  @RestController
Let's add `server.servlet.context-path=/api` into application.properties file:
`@RequestMapping("/books")`

2024-05-14 21:43 UTC, DanilKi commented
I have a question regarding the update operation. Is there any way to perform an UPDATE without performing a SELECT before it, using JpaRepository? I tried several variants, but Hibernate fetches entity from DB by select stmt, before update statement (I saw that in console) or I get LazyInitEx. I mean, maybe there are some standard methods exist, without declaring custom method with @Query annotation and writing SQL statement in it?

2024-05-15 06:28 UTC, Elena-Bruyako approved these changes
Minor comment
let's discuss your question in chat

2024-05-15 06:28 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/mapper/BookMapper.java
> +    Book toBookEntity(CreateBookRequestDto requestDto, @MappingTarget Book book);
```suggestion
    void toBookEntity(CreateBookRequestDto requestDto, @MappingTarget Book book);
```

2024-05-15 06:28 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/BookServiceImpl.java
> +        book = bookMapper.toBookEntity(requestDto, book);
```suggestion
        bookMapper.toBookEntity(requestDto, book);
```

2024-05-15 08:15 UTC, merged